#!/usr/bin/env bash

# v0.1
# This is a nagios/icinga plugin reporting fc hba status and speed
# For more details see https://github.com/ethbian/check_fc_hba

fcpath='/sys/class/fc_host'
number=2
speed=8
msg='FC status -'
help=false

while getopts n:s:o:h option
do
   case "${option}" in
      n)number=${OPTARG};;
      s)speed=${OPTARG};;
      o)online=${OPTARG};;
      h)help=true;;
   esac
done


if [ "$help" = true ]; then
cat << EOF
Usage: 
 $0
   -s (speed in Gbit, default: $speed)
   -n (number of FC ports, default: $number)
   -o (number of Online FC host, default = number of FC ports)

   example: expecting 2 FC ports with 16 Gbit speed, all should be Online:
   $0 -n 2 -s 16

   output: CRITICAL when wrong number of FC ports or port state not being Online
           WARNING when speed different from expected

EOF
   exit 0
fi

if [ "$online" == "" ]; then
   online=$number
fi

if [ ! -d "$fcpath" ]; then
   echo 'CRITICAL: FC ports not found'
   exit 2
fi

online_critical=false
online_number=0

for fcfile in $(ls $fcpath); do
   state_file="${fcpath}/${fcfile}/port_state"
   found=$(grep -c Online "$state_file")
   real_state=$(cut -f 1 -d " " "$state_file")
   if [ "$found" -gt 0 ]; then
      online_number=$((online_number + 1))
      msg="$msg $fcfile: $real_state, "
   else
      msg="$msg $fcfile: $real_state, "
   fi
done

if [ "$online" -ne "$online_number" ]; then
   online_critical=true
fi

speed_warning=false
for fcfile in $(ls $fcpath); do
   speed_file="${fcpath}/${fcfile}/speed"
   if [ -f "$speed_file" ]; then
      found=$(grep -c "^${speed} Gbit" "$speed_file")
      real_speed=$(cut -f 1 -d " " "$speed_file")
      if [ "$found" -eq 0 ]; then
         speed_warning=true
         msg="$msg $fcfile speed: $real_speed, "
      else
         msg="$msg $fcfile speed: $real_speed, "
      fi
   else
      speed_warning=true
      msg="$msg $fcfile speed: -, "
   fi
done

number_critical=false
fchosts=$(ls $fcpath |wc -l)
if [ ! "$fchosts" -eq "$number" ]; then
  number_critical=true
  msg="$msg FC port number: $fchosts (expecting $number)"
else
  msg="$msg FC port number: $fchosts"
fi

if [ "$online_critical" = true -o "$number_critical" = true ]; then
   echo "CRITICAL: $msg"
   exit 2
elif [ "$speed_warning" = true ]; then
   echo "WARNING: $msg"
   exit 1
else
   echo "OK: $msg"
   exit 0
fi

